name: commitlint
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  commitlint:
    uses: cffnpwr/actions/.github/workflows/commitlint.yaml@ef7120284c6d7078936b92d94cc2ba36606c44f9 # main
    permissions:
      contents: read
