name: Semantic PR title
on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  pull-requests: read

jobs:
  semantic-pr-title:
    uses: cffnpwr/actions/.github/workflows/semantic-pr-title.yaml@cffbe45017ccd73dc466a078833fbb4ca231e684 # main
